/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SurfacesRouteImport } from './routes/surfaces'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DmcaDisclaimerRouteImport } from './routes/dmca-disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaDisclaimerRoute = DmcaDisclaimerRouteImport.update({
  id: '/dmca-disclaimer',
  path: '/dmca-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/architecture': typeof ArchitectureRoute
  '/contact': typeof ContactRoute
  '/dmca-disclaimer': typeof DmcaDisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surfaces': typeof SurfacesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/architecture': typeof ArchitectureRoute
  '/contact': typeof ContactRoute
  '/dmca-disclaimer': typeof DmcaDisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surfaces': typeof SurfacesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/architecture': typeof ArchitectureRoute
  '/contact': typeof ContactRoute
  '/dmca-disclaimer': typeof DmcaDisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surfaces': typeof SurfacesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise'
    | '/architecture'
    | '/contact'
    | '/dmca-disclaimer'
    | '/editorial-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/surfaces'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/architecture'
    | '/contact'
    | '/dmca-disclaimer'
    | '/editorial-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/surfaces'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise'
    | '/architecture'
    | '/contact'
    | '/dmca-disclaimer'
    | '/editorial-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/surfaces'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ContactRoute: typeof ContactRoute
  DmcaDisclaimerRoute: typeof DmcaDisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurfacesRoute: typeof SurfacesRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca-disclaimer': {
      id: '/dmca-disclaimer'
      path: '/dmca-disclaimer'
      fullPath: '/dmca-disclaimer'
      preLoaderRoute: typeof DmcaDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  ArchitectureRoute: ArchitectureRoute,
  ContactRoute: ContactRoute,
  DmcaDisclaimerRoute: DmcaDisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurfacesRoute: SurfacesRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
